import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
padding.x = 10
padding.y = 10
opacity = 0.98
option_as_alt = "OnlyRight"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 16

[keyboard]
bindings = [
    # ⌘ + enter puts window in macOS full screen
    { key = "Enter", mods = "Command", action = "ToggleFullscreen"}
]

